spring:
   application:
      name: CONFIG-SERVER
   banner:
    location: classpath:banner.txt
   cloud:
      config:
         server:
            git:
               uri: https://github.com/usamal-pixel/cloud-config-server
server:
   port: 8888
   
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
     hostname: localhost  
   